version: '3.7'
services:
    web:
        image: apache
        build: ./webapp
        container_name: apache_web
        restart: always
        ports:
          - "8080:80"
    jenkins:
        build: ./jenkins
        container_name: jenkins
        privileged: true
        restart: always
        ports:
          - "8081:8080"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/bin/docker

    registry:
        image: registry
        container_name: registrynew
        restart: always
        ports:
          - "5001:5000"

